### ISSUE TITLE
Add custom projectile behaviour definition

### ISSUE THREAD

**Issue by Intybyte** [Intybyte/Cannons#41]
Right now all projectile types follow vanilla behaviour, it would be nice to allow people to define their custom projectile behaviour with drag, water drag and gravity.

For instance allow people to define a projectile:

```yaml
"my_server_namespace:fancy_arrow":
    base_entity: "minecraft:arrow"
    drag: 1.0 // default is 0.99, now the arrow won't slow down at all during movement
    water_drag: 0.5 // default is 0.6, now the arrow will slow down faster in water
    gravity: -0.01 // default is 0.05, now arrow goes slighly up instead of falling

```
